# Autocompletion
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH
fi

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# theme
ZSH_THEME=""

# https://github.com/sindresorhus/pure
fpath+=("$HOME/.config/zsh/pure")
autoload -U promptinit; promptinit
prompt pure

# Plugins
plugins=(fzf git z colored-man-pages colorize pip python brew osx)
source $ZSH/oh-my-zsh.sh

# User
export LANG="en_US.UTF-8"

# asdf
export ASDF_CONFIG_FILE="~/.config/asdf/.asdfrc"
. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash

# TMUX
export TMUX_CONFIG="~/.config/tmux/.tmux.conf"
alias tm="tmux -f $TMUX_CONFIG -u attach || tmux -f $TMUX_CONFIG -u new"

# Weechat
alias weechat="weechat -d ~/.config/weechat"

# to get autosuggestion to work properly with color in tmux
export TERM=xterm-256color

# Alias
alias l='ls -lAFh'    #long list,show almost all,show type,human readable
alias ll='l'
alias vim='nvim'

# ZFZ Fuzzy search
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# zsh completions
fpath=(/usr/local/share/zsh-completions $fpath)

# zsh autosuggestions
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# zsh highlightning
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
export ZSH_HIGHLIGHT_HIGHLIGHTERS_DIR=/usr/local/share/zsh-syntax-highlighting/highlighters
