export ZSH=$HOME/.oh-my-zsh
export EDITOR='nvim'
export CONFIG=$HOME/.config
export TMUX_CONFIG="$CONFIG/tmux/.tmux.conf"
export ASDF_CONFIG_FILE="$CONFIG/asdf/.asdfrc"
export FZF_DEFAULT_COMMAND='rg --files'

case `uname` in
  Darwin)
    source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
    source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
  ;;
  Linux)
    source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
    source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
  ;;
esac

#export LANG="en_US.UTF-8"

# theme
ZSH_THEME="spaceship"

# spaceship promt
SPACESHIP_PACKAGE_SHOW=false

#  https://formulae.brew.sh/formula/zsh-completion
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH

  autoload -Uz compinit
  compinit
fi

# zsh plugins
plugins=(fzf git z colorize brew)
source $ZSH/oh-my-zsh.sh

# asdf
. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash

# ZFZ Fuzzy search
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


# zsh completions
fpath=(/usr/local/share/zsh-completions $fpath)

# zsh autosuggestions
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#4d5966'

# zsh highlightning
export ZSH_HIGHLIGHT_HIGHLIGHTERS_DIR=/usr/local/share/zsh-syntax-highlighting/highlighters

source $HOME/.zshfunctions
source $HOME/.zshalias
