# Autocompletion
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH
fi

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# theme
ZSH_THEME="spaceship"

# spaceship promt
SPACESHIP_PACKAGE_SHOW=false
SPACESHIP_NODE_SHOW=false
SPACESHIP_CHAR_SUFFIX=" "

# Plugins
plugins=(fzf git z colored-man-pages colorize pip python brew osx)
source $ZSH/oh-my-zsh.sh

# User
export LANG="en_US.UTF-8"

# asdf
export ASDF_CONFIG_FILE="~/.config/asdf/.asdfrc"
. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash

# TMUX
export TMUX_CONFIG="~/.config/tmux/.tmux.conf"
alias tm="tmux -f $TMUX_CONFIG -u attach || tmux -f $TMUX_CONFIG -u new"

# Weechat
alias weechat="weechat -d ~/.config/weechat"

# to get autosuggestion to work properly with color in tmux
# export TERM=xterm-256color
# Enabled true color support for terminals
export NVIM_TUI_ENABLE_TRUE_COLOR=1

# Alias
alias l='ls -lAFh'    #long list,show almost all,show type,human readable
alias ll='l'
alias vim='nvim'
alias gps='gh pr status'

# Set default editor to nvim
export EDITOR='nvim'

# Setting rg as the default source for fzf
export FZF_DEFAULT_COMMAND='rg --files'

# fcb [FUZZY PATTERN] - Checkout specified branch
# Include remote branches, sorted by most recent commit and limited to 30
fcb() {
  local branches branch
  branches=$(git for-each-ref --count=30 --sort=-committerdate refs/heads/ --format="%(refname:short)") &&
  branch=$(echo "$branches" |
           fzf-tmux -d $(( 2 + $(wc -l <<< "$branches") )) +m) &&
  git checkout $(echo "$branch" | sed "s/.* //" | sed "s#remotes/[^/]*/##")
}

# ZFZ Fuzzy search
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# zsh completions
fpath=(/usr/local/share/zsh-completions $fpath)

# zsh autosuggestions
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# zsh highlightning
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
export ZSH_HIGHLIGHT_HIGHLIGHTERS_DIR=/usr/local/share/zsh-syntax-highlighting/highlighters
